[features]
seeds = false
[programs.localnet]
launchpad_demo = "n7g1A1RFUJNSUdfvgWE7dqf7G9QoBbBguTZdUM94HdL"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "./service_wallet.json"

[provider]
cluster = "devnet"
wallet = "./service_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
